In [1]:
import numpy as np

In [2]:
arr=np.array([[2,2],[3,4]])

In [3]:
arr

array([[2, 2],
       [3, 4]])

In [4]:
np.sum(arr,axis=0)

array([5, 6])

In [5]:
np.sum(arr,axis=1)

array([4, 7])

In [6]:
np.mean(arr,axis=0)

array([2.5, 3. ])

In [7]:
np.std(arr,axis=1)

array([0. , 0.5])

In [8]:
np.min(arr)

2

In [9]:
np.max(arr)

4

In [11]:
np.min(arr,axis=1)

array([2, 3])

In [12]:
np.argmin(arr)

0

In [15]:
np.argmax(arr,axis=0)

array([1, 1])

In [18]:
median = np.percentile(arr, 70,axis=0)

In [19]:
median

array([2.7, 3.4])

In [20]:
b=arr>2

In [22]:
selected=arr[b]

In [24]:
selected

array([3, 4])

In [27]:
arr[arr>2] = 7

In [39]:
arr

array([2, 9, 9, 9, 2, 7, 7])

In [29]:
print(np.arange(1, 10))

[1 2 3 4 5 6 7 8 9]


In [31]:
print(np.linspace(1, 10, 4))

[ 1.  4.  7. 10.]


In [58]:
print(np.random.randint(low=5,high=10, size=(10,2))

SyntaxError: unexpected EOF while parsing (3210006087.py, line 1)

In [34]:
arr.shape

(2, 2)

In [37]:
arr

array([2, 9, 9, 2, 7, 7])

In [44]:
new=np.array([[1,3],[5,7]])

In [45]:
new

array([[1, 3],
       [5, 7]])

In [49]:
a=np.arange(10)

In [50]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [54]:
arr = np.array([1, 2, 3, 4, 5, 6])

arr.resize(3, 4)
print(arr)

[[1 2 3 4]
 [5 6 0 0]
 [0 0 0 0]]
