In [1]:
import numpy as np

In [7]:
a=np.random.randint(100,size=(7,24))

In [8]:
a

array([[10, 88, 84, 30, 30, 70, 70, 66, 50, 36, 60, 47, 17, 45, 99, 52,
        31,  4, 34, 29, 60, 92, 69, 57],
       [63,  8,  7, 43, 35, 47, 95, 68, 68, 81, 62, 63,  9, 64, 53, 75,
        81,  4, 30, 47, 71, 78, 17, 40],
       [51, 15, 85, 38, 16, 61, 87, 30, 33, 40, 68, 27, 34, 82, 49, 42,
        19,  0, 55, 41, 85, 84, 65, 86],
       [29, 68, 49,  5, 90, 39, 75, 93, 93, 22, 38, 43, 65, 60, 70, 61,
        87,  8, 46, 80,  4, 91, 23, 80],
       [27,  5, 19, 20, 65, 80, 89, 23, 90,  9, 34, 88, 18, 92, 92, 71,
         7, 83,  9, 84, 35, 99, 78,  0],
       [78, 15, 20, 49, 72, 27, 36, 92, 20, 48, 24, 41, 31, 25, 55, 15,
        37,  4, 91, 47, 54, 98, 18, 33],
       [86, 44, 67, 33, 63, 56, 63, 31, 63, 69, 95, 13, 41, 22, 81, 10,
        13, 42, 72, 26, 48, 57,  3, 81]])

In [6]:
arr=np.array([[1],[2],[3],[4],[5],[6],[7]])

In [14]:
new=np.concatenate((arr,a,),axis=1)

In [15]:
new

array([[ 1, 10, 88, 84, 30, 30, 70, 70, 66, 50, 36, 60, 47, 17, 45, 99,
        52, 31,  4, 34, 29, 60, 92, 69, 57],
       [ 2, 63,  8,  7, 43, 35, 47, 95, 68, 68, 81, 62, 63,  9, 64, 53,
        75, 81,  4, 30, 47, 71, 78, 17, 40],
       [ 3, 51, 15, 85, 38, 16, 61, 87, 30, 33, 40, 68, 27, 34, 82, 49,
        42, 19,  0, 55, 41, 85, 84, 65, 86],
       [ 4, 29, 68, 49,  5, 90, 39, 75, 93, 93, 22, 38, 43, 65, 60, 70,
        61, 87,  8, 46, 80,  4, 91, 23, 80],
       [ 5, 27,  5, 19, 20, 65, 80, 89, 23, 90,  9, 34, 88, 18, 92, 92,
        71,  7, 83,  9, 84, 35, 99, 78,  0],
       [ 6, 78, 15, 20, 49, 72, 27, 36, 92, 20, 48, 24, 41, 31, 25, 55,
        15, 37,  4, 91, 47, 54, 98, 18, 33],
       [ 7, 86, 44, 67, 33, 63, 56, 63, 31, 63, 69, 95, 13, 41, 22, 81,
        10, 13, 42, 72, 26, 48, 57,  3, 81]])

In [16]:
print(new)

[[ 1 10 88 84 30 30 70 70 66 50 36 60 47 17 45 99 52 31  4 34 29 60 92 69
  57]
 [ 2 63  8  7 43 35 47 95 68 68 81 62 63  9 64 53 75 81  4 30 47 71 78 17
  40]
 [ 3 51 15 85 38 16 61 87 30 33 40 68 27 34 82 49 42 19  0 55 41 85 84 65
  86]
 [ 4 29 68 49  5 90 39 75 93 93 22 38 43 65 60 70 61 87  8 46 80  4 91 23
  80]
 [ 5 27  5 19 20 65 80 89 23 90  9 34 88 18 92 92 71  7 83  9 84 35 99 78
   0]
 [ 6 78 15 20 49 72 27 36 92 20 48 24 41 31 25 55 15 37  4 91 47 54 98 18
  33]
 [ 7 86 44 67 33 63 56 63 31 63 69 95 13 41 22 81 10 13 42 72 26 48 57  3
  81]]


In [17]:
np.mean(new[:,1:])

49.86309523809524

In [19]:
np.sum(new[:,1:],axis=1)

array([1230, 1209, 1193, 1319, 1217, 1030, 1179])

In [20]:
np.var(new[:,1:],axis=1)

array([ 637.10416667,  684.15104167,  653.95659722,  814.28993056,
       1226.53993056,  674.32638889,  653.859375  ])

In [21]:
np.std(new[:,1:],axis=1)

array([25.24092246, 26.15628111, 25.5725751 , 28.53576581, 35.0219921 ,
       25.96779523, 25.57067412])

In [22]:
np.mean(new[:,1:],axis=1)

array([51.25      , 50.375     , 49.70833333, 54.95833333, 50.70833333,
       42.91666667, 49.125     ])