In [1]:
import numpy as np

In [5]:
 np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [13]:
np.random.rand(1,2)

array([[0.8517823 , 0.55636054]])

In [17]:
b=np.random.random((2,2))

In [22]:
b.dtype

dtype('float64')

In [50]:
a = np.arange(12).reshape(3, 4)


# #array([[ 0,  1,  2,  3],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11]])

i = np.array([[0, 1],  # indices for the first dim of `a`

              [1, 1]])

j = np.array([[1, 2],  # indices for the second dim

              [2, 3]])

In [51]:

a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
i

array([[0, 1],
       [1, 1]])

In [53]:
j

array([[1, 2],
       [2, 3]])

In [58]:
b=a[i, j].flatten()

In [60]:
np.delete(b,1)

array([1, 6, 7])

In [33]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
result = np.split(arr, 2, axis=0) # Split along axis 0 (rows) into 2 sub-arrays
print(result)
# Output: [array([[1, 2], [3, 4]]), array([[5, 6], [7, 8]])]


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [34]:
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [61]:
arr.sum()

36

In [66]:
arr.reshape(4,-1)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [72]:
arr.reshape(2,-1,order='F')

array([[1, 5, 2, 6],
       [3, 7, 4, 8]])

In [73]:
arr.diagonal()

array([1, 4])

In [75]:
b=arr[::-1]

In [76]:
b

array([[7, 8],
       [5, 6],
       [3, 4],
       [1, 2]])

In [80]:
c=arr.T

In [81]:
c

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [86]:
import numpy as np

arr_1d = np.array([[8, 2, 0, 1],[4,5,6,8]])
sorted_arr_1d = np.sort(arr_1d,axis=1)
print("Sorted 1D array:", sorted_arr_1d)

arr_2d = np.array([[3, 10, 2], [1, 5, 7], [2, 7, 5]])
sorted_arr_2d = np.sort(arr_2d,axis=0) # Sorts along the last axis (axis=1) by default
print("Sorted 2D array (default axis):\n", sorted_arr_2d)


Sorted 1D array: [[0 1 2 8]
 [4 5 6 8]]
Sorted 2D array (default axis):
 [[ 1  5  2]
 [ 2  7  5]
 [ 3 10  7]]


In [89]:
a=np.arange(30)

In [94]:
a.reshape(3,2,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])