In [2]:
import numpy as np
raw = np.array([[1,2,np.nan] , [ 4,np.nan,6] , [np.nan,8,9]])

In [3]:
raw

array([[ 1.,  2., nan],
       [ 4., nan,  6.],
       [nan,  8.,  9.]])

In [4]:
mean_value=np.nanmean(raw)

In [6]:
mean_value

5.0

In [10]:
raw[np.isnan(raw)] = mean_value

In [11]:
raw

array([[1., 2., 5.],
       [4., 5., 6.],
       [5., 8., 9.]])

In [12]:
np.min(raw)

1.0

In [13]:
np.max(raw)

9.0

In [14]:
np.std(raw)

2.4037008503093262

In [16]:
a=np.var(raw)

In [17]:
std=np.sqrt(a)

In [18]:
std

2.4037008503093262

In [19]:
frequency = raw *5/9 +32

In [20]:
frequency

array([[32.55555556, 33.11111111, 34.77777778],
       [34.22222222, 34.77777778, 35.33333333],
       [34.77777778, 36.44444444, 37.        ]])

In [21]:
np.max(frequency)

37.0

In [22]:
np.min(frequency)

32.55555555555556