In [1]:
import numpy as np

In [5]:
arr=np.array([[1,8],[2,5,],[3,7],[4,9]])

In [6]:
arr

array([[1, 8],
       [2, 5],
       [3, 7],
       [4, 9]])

In [10]:
b=arr[:,1:]

In [13]:
b.mean()

7.25

In [15]:
a=np.mean(arr[:,1:],axis=0)

In [16]:
a

array([7.25])

In [17]:
np.max(arr,axis=0)

array([4, 9])

In [18]:
np.sort(arr)

array([[1, 8],
       [2, 5],
       [3, 7],
       [4, 9]])

In [19]:
a=np.array([[1,2],[3,4]])
b=np.array([6,7])

In [20]:
c=a+b

In [21]:
c

array([[ 7,  9],
       [ 9, 11]])

In [34]:
b=np.ones([2,3])

In [35]:
a= np.zeros([3,3])

In [36]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [49]:
a=np.array([[1],[2],[3],[4]])

In [50]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
a+b

ValueError: operands could not be broadcast together with shapes (4,1) (2,3) 

In [52]:
print(np.random.randint(low=5,high=10, size=(10,2))

SyntaxError: unexpected EOF while parsing (3210006087.py, line 1)