In [1]:
pip install numpy


  Using cached numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install pandas


  Using cached pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
  Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
  Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install seaborn


     |████████████████████████████████| 294 kB 273 kB/s eta 0:00:01
     |████████████████████████████████| 9.2 MB 2.2 MB/s eta 0:00:01
     |████████████████████████████████| 301 kB 2.5 MB/s eta 0:00:01
     |████████████████████████████████| 4.7 MB 2.3 MB/s eta 0:00:01
     |████████████████████████████████| 1.2 MB 1.6 MB/s eta 0:00:01
     |████████████████████████████████| 104 kB 3.5 MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [45]:
import numpy as np

In [46]:
d=np.array([1,2])

TypeError: 'list' object is not callable

In [3]:
d

array([1, 2])

In [7]:
d2=np.array([[1,2],[3,4]])

In [8]:
d2


array([[1, 2],
       [3, 4]])

In [6]:
d3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [7]:
d3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [8]:
print(d3.ndim) 

3


In [9]:
a= np.array([2,4,5,6])

In [10]:
c=a[0] + a[2]
print(c)

7


In [11]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])




In [12]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [13]:
print(arr.shape)

(2, 2, 3)


In [14]:
print(arr[1,1,2])

12


In [15]:
arr2=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])

In [16]:
arr2.ndim

3

In [17]:
arr2

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [18]:
arr2[::-1]

array([[[ 9, 10],
        [11, 12]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 1,  2],
        [ 3,  4]]])

In [19]:
arr2.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [20]:
c=arr2.reshape(4,1,3)

In [21]:
c.ndim

3

In [22]:
c.shape

(4, 1, 3)

In [23]:
arr=np.zeros([2,2])
arr

array([[0., 0.],
       [0., 0.]])

In [24]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:1])


[2 3 4 5]


In [25]:
arr = np.array(['3', '2', '3'], dtype='S')
print(arr)


[b'3' b'2' b'3']


In [26]:
arr.dtype

dtype('S1')

In [27]:
import numpy as np
arr2=np.array([4,5,6,7])

x=arr2.copy()
arr2[1]=49

print(arr2)
print(x)

[ 4 49  6  7]
[4 5 6 7]


In [2]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y) 

1
2
3
4
5
6


In [1]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)


1
2
3
4
5
6
7
8
9
10
11
12


In [1]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])

for x in np.nditer(arr):
  print(x)


1
2
3
4


In [9]:
arr = np.array([[1, 2], [3, 4]])
print(arr[1::])

[[3 4]]


In [1]:

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x) 

1
3
5
7


In [1]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [5]:

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr) 

[[1 2 5 6]
 [3 4 7 8]]


In [3]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr) 

[[1 4]
 [2 5]
 [3 6]]


In [11]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=0)

print(arr) 

[[1 2 3]
 [4 5 6]]


In [8]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr) 

[1 2 3 4 5 6]


In [10]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr) 

[[1 2 3]
 [4 5 6]]


In [12]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [13]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)


[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [31]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x) 

(array([1, 3, 5, 7]),)


In [41]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x) 

TypeError: 'list' object is not callable

In [1]:
import numpy as np
arr=np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])
arr

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [36]:
print(arr[0,0,2])

3


In [37]:
print(arr[1, 0,2])

6


In [18]:
print(arr[2,0,2])

9


In [30]:
arr

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [35]:
print(arr[ :2, : ,1:2])

[[[2]]

 [[5]]]


In [28]:
d2

array([[1, 2],
       [3, 4]])

In [13]:
print(d2[:1,0:])

[[1 2]]


In [41]:
arr=[[[2,3,5]],[[3,6,7]]]
arr=np.array(arr,dtype="f")


In [42]:
arr

array([[[2., 3., 5.]],

       [[3., 6., 7.]]], dtype=float32)

In [43]:
print(arr[0, 0,1])

3.0


In [45]:
print(arr[: 1, : ,:2])

[[[2. 3.]]]


In [46]:
arr=np.array([2,3,6,7])
a=arr.reshape(2,2)
print(a)

[[2 3]
 [6 7]]


In [48]:
a.flatten(order='f')

array([2, 6, 3, 7])

In [49]:
array_1 = np.array([[1,2,3],[0,0,0]])
array_2 = np.array([[0,0,0],[7,8,9]])
arr= np.vstack((array_1, array_2))

In [58]:
print(arr)

[[1 2 3]
 [0 0 0]
 [0 0 0]
 [7 8 9]]


In [63]:

np.delete(arr, 2,0)

array([[1, 2, 3],
       [0, 0, 0],
       [7, 8, 9]])

In [64]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result_column = np.delete(array_2d, 0, axis=1)
print(result_column)  # for deleting a row axis =0

[[2 3]
 [5 6]
 [8 9]]
