In [13]:
import numpy as np


In [16]:
arr=np.array([[1,-2,6],[3,4,76],[54,-8,98]])

In [17]:
print(arr)

[[ 1 -2  6]
 [ 3  4 76]
 [54 -8 98]]


In [18]:

np.where(arr<0,0,arr)

    

array([[ 1,  0,  6],
       [ 3,  4, 76],
       [54,  0, 98]])

In [19]:
np.count_nonzero(arr>30)

3